version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7
    working_directory: /home/circleci/dogfighter
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - deploy:
          name: Digital Oceans
          command: ssh -o "StrictHostKeyChecking no" root@104.131.171.193 'cd ~/dogfight-server && git pull && npm install && forever stopall && forever start server/index.js'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
