version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7
    working_directory: /
    steps:
      - run:
          command: echo "hi"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deployment:
          development:
            branch: master
            codedeploy:
              Dogfighter:
                development_group: development

