version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.3
    working_directory: /
    steps:
      - run:
          name: Install and run pm2
          command: npm install && npm install -g pm2

workflows:
  build-deploy:
    jobs:
      - build
      - deployment:
          development:
            branch: master
            codedeploy:
              Dogfighter:
                development_group: development

