version: 2
jobs:
  build:
    working_directory: /
    steps:
      - run: npm -v

  deploy-job:
    working_directory: /
    steps:
      - run:
          name: Install some stuff
          command: npm install
      - run:
          name: Deploy if tests pass and branch is Master
          command: aws s3 sync ec2-user/_site/docs s3://dogfighter-deployments/docs/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master

