version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7
    working_directory: /
    steps:
      - run:
          command: echo "hi"

  deploy:
    docker:
      - image: node:6.10
    working_directory: ~/dogfighter
    steps:
      - run:
          command: |
            apt-get -y -qq update
            apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            pip install awscli --upgrade --user
            echo "export PATH=~/.local/bin:$PATH" >> ~/.bash_profile
            source ~/.bash_profile
            aws s3 sync ~/dogfighter s3://dogfighter-deployments/docs/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy
