version: 2
deploy-job:
  working_directory: /
  steps:
    - run:
      name: Deploy to S3
      command: aws s3 sync /var/www/html s3://dogfighter-deployments/docs/ --delete

build:
  steps:
    - run:
      name: Say something
      command: echo "Hi"

workflows:
  jobs:
    - build
    - deploy-job
      filters:
        branches:
          only: master
