version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7
    working_directory: /home/circleci/dogfighter
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Building
          command:
            npm run build-dev

      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
  deploy:
    working_directory: /home/circleci/dogfighter
    docker:
      - image: node:6.10
    steps:
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH} && pwd && ls
      # Restore cache from build job
      # dist folder
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: Install AWS CLI
          command: |
            apt-get -y -qq update
            apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            echo "export PATH=~/.local/bin:$PATH" >> ~/.bash_profile
            source ~/.bash_profile
            pip install awscli --upgrade --user
            source ~/.bash_profile
            aws --region us-west-2 s3 sync dist s3://dogfighter-deployments/releases/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
