version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7
    working_directory: /
    steps:
      - run:
        commands:
          - npm install -g pm2

workflows:
  build-deploy:
    jobs:
      - build
      - deployment:
          development:
            branch: master
            codedeploy:
              Dogfighter:
                development_group: development

