deploy-job:
  working_directory: /
  steps:
    - run:
      name: Deploy to S3
      command: aws s3 sync /var/www/html s3://dogfighter-deployments/docs/ --delete

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy-job
        filters:
          branches:
            only: master
